from osdagbridge.core.utils.common import (
    SAIL_APPROVED_THICKNESS_VALUES,
    VALUES_BEARING_STIFFENER_COUNT,
    VALUES_END_DIAPHRAGM_TYPE,
    VALUES_GIRDER_DESIGN_MODE,
    VALUES_GIRDER_SPAN_MODE,
    VALUES_GIRDER_SUPPORT_TYPE,
    VALUES_GIRDER_SYMMETRY,
    VALUES_GIRDER_TYPE,
    VALUES_LONGITUDINAL_STIFFENER,
    VALUES_PROFILE_SCOPE,
    VALUES_STIFFENER_DESIGN,
    VALUES_TORSIONAL_RESTRAINT,
    VALUES_WARPING_RESTRAINT,
    VALUES_WEB_TYPE,
    VALUES_NO_YES,
    STIFFENER_DETAILS_DEFAULTS,
)

GIRDER_DETAILS_SCHEMA = {
    "id": "girder_details_tab",
    "defaults": {
        "member_length_m": 30.0,
        "distance_start_m": 0.0,
        "max_girder_count": 20,
    },
    "SAIL_APPROVED_THICKNESS_VALUES": SAIL_APPROVED_THICKNESS_VALUES,
    "thickness_values_mm": SAIL_APPROVED_THICKNESS_VALUES,
    "overview": [
        {
            "id": "select_girder",
            "label": "Select Girder:",
            "type": "combo_dynamic",
            "bind": "girder_dropdown",
            "include_all": True,
        },
        {
            "id": "span",
            "label": "Span:",
            "type": "combo",
            "choices": VALUES_GIRDER_SPAN_MODE,
            "bind": "span_combo",
        },
        {
            "id": "total_span",
            "label": "Total Span (m):",
            "type": "line",
            "default": "30",
            "read_only": True,
            "bind": "length_input",
        },
    ],
    "segment_manager": {
        "table_headers": ["Member ID", "Start (m)", "End (m)", "Length (m)", "Action"],
        "action_column_width": 132,
    },
    "cad_view": {
        "buttons": [
            {"id": "cross_section", "label": "Cross Section", "mode": "cross", "width": 130, "height": 32},
            {"id": "side_view", "label": "Side View", "mode": "side", "width": 130, "height": 32},
        ]
    },
    "section_inputs": [
        {
            "id": "design",
            "label": "Design:",
            "type": "combo",
            "choices": VALUES_GIRDER_DESIGN_MODE,
            "bind": "design_combo",
            "legacy_payload_key": "design_mode",
            "visible_for": ["welded"],
        },
        {
            "id": "type",
            "label": "Type:",
            "type": "combo",
            "choices": VALUES_GIRDER_TYPE,
            "bind": "type_combo",
            "legacy_payload_key": "girder_type",
        },
        {
            "id": "symmetry",
            "label": "Symmetry:",
            "type": "combo",
            "choices": VALUES_GIRDER_SYMMETRY,
            "bind": "symmetry_combo",
            "row_bucket": "symmetry_row",
            "legacy_payload_key": "symmetry",
            "visible_for": ["welded"],
        },
        {
            "id": "depth",
            "label": "Total Depth, d (mm):",
            "type": "line_with_bounds",
            "bounds_key": "total_depth",
            "bounds_default": {"lower": 200.0, "upper": 2000.0, "increment": 25.0},
            "bind": "total_depth_input",
            "bind_widget": "total_depth_widget",
            "bind_bounds_button": "total_depth_bounds_button",
            "legacy_welded_key": "total_depth_mm",
            "legacy_welded_bounds_key": "total_depth_bounds",
            "visible_for": ["welded"],
        },
        {
            "id": "top_flange_width",
            "label": "Width of Top Flange, t<sub>fw</sub> (mm):",
            "type": "line_with_bounds",
            "bounds_key": "top_width",
            "bounds_default": {"lower": 100.0, "upper": 1000.0, "increment": 10.0},
            "bind": "top_width_input",
            "bind_widget": "top_width_widget",
            "bind_bounds_button": "top_width_bounds_button",
            "legacy_welded_key": "top_flange_width_mm",
            "legacy_welded_bounds_key": "top_flange_width_bounds",
            "visible_for": ["welded"],
        },
        {
            "id": "top_flange_thickness",
            "label": "Top Flange Thickness, t<sub>ft</sub> (mm):",
            "type": "mode_line",
            "mode_choices": VALUES_PROFILE_SCOPE,
            "default_mode": "All",
            "bind_mode": "top_thickness_combo",
            "bind_value": "top_thickness_value_input",
            "bind_wrapper": "top_thickness_widget",
            "thickness_key": "top_thickness",
            "legacy_welded_mode_key": "top_thickness_mode",
            "legacy_welded_value_key": "top_thickness_value_mm",
            "visible_for": ["welded"],
        },
        {
            "id": "bottom_flange_width",
            "label": "Width of Bottom Flange, b<sub>fw</sub> (mm):",
            "type": "line_with_bounds",
            "bounds_key": "bottom_width",
            "bounds_default": {"lower": 100.0, "upper": 1000.0, "increment": 10.0},
            "bind": "bottom_width_input",
            "bind_widget": "bottom_width_widget",
            "bind_bounds_button": "bottom_width_bounds_button",
            "legacy_welded_key": "bottom_flange_width_mm",
            "legacy_welded_bounds_key": "bottom_flange_width_bounds",
            "visible_for": ["welded"],
        },
        {
            "id": "bottom_flange_thickness",
            "label": "Bottom Flange Thickness, b<sub>ft</sub> (mm):",
            "type": "mode_line",
            "mode_choices": VALUES_PROFILE_SCOPE,
            "default_mode": "All",
            "bind_mode": "bottom_thickness_combo",
            "bind_value": "bottom_thickness_value_input",
            "bind_wrapper": "bottom_thickness_widget",
            "thickness_key": "bottom_thickness",
            "legacy_welded_mode_key": "bottom_thickness_mode",
            "legacy_welded_value_key": "bottom_thickness_value_mm",
            "visible_for": ["welded"],
        },
        {
            "id": "support_type",
            "label": "Support Type:",
            "type": "combo",
            "choices": VALUES_GIRDER_SUPPORT_TYPE,
            "bind": "support_type_combo",
            "visible_for": ["welded"],
        },
        {
            "id": "support_width",
            "label": "Support Width (mm):",
            "type": "line",
            "validator": {"type": "double_range", "bottom": 0.0, "top": 1000000.0, "decimals": 3},
            "bind": "support_width_input",
            "legacy_welded_key": "support_width_mm",
            "visible_for": ["welded"],
        },
        {
            "id": "web_thickness",
            "label": "Web Thickness, w<sub>t</sub> (mm):",
            "type": "mode_line",
            "mode_choices": VALUES_PROFILE_SCOPE,
            "default_mode": "All",
            "bind_mode": "web_thickness_combo",
            "bind_value": "web_thickness_value_input",
            "bind_wrapper": "web_thickness_widget",
            "thickness_key": "web_thickness",
            "legacy_welded_mode_key": "web_thickness_mode",
            "legacy_welded_value_key": "web_thickness_value_mm",
            "visible_for": ["welded"],
        },
        {
            "id": "is_section",
            "label": "IS Section:",
            "type": "combo",
            "choices": [
                "ISMB 500", "ISMB 550", "ISMB 600",
                "ISWB 500", "ISWB 550", "ISWB 600",
            ],
            "bind": "is_section_combo",
            "legacy_payload_key": "rolled_section",
            "visible_for": ["rolled"],
        },
        {
            "id": "torsional_restraint",
            "label": "Torsional Restraint:",
            "type": "combo",
            "choices": VALUES_TORSIONAL_RESTRAINT,
            "bind": "torsion_combo",
            "aliases": ["torsion"],
            "legacy_payload_key": "torsional_restraint",
        },
        {
            "id": "warping_restraint",
            "label": "Warping Restraint:",
            "type": "combo",
            "choices": VALUES_WARPING_RESTRAINT,
            "bind": "warping_combo",
            "aliases": ["warping"],
            "legacy_payload_key": "warping_restraint",
        },
        {
            "id": "web_type",
            "label": "Web Type:",
            "type": "combo",
            "choices": VALUES_WEB_TYPE,
            "bind": "web_type_combo",
            "row_bucket": "web_type_row",
            "legacy_payload_key": "web_type",
            "visible_for": ["welded"],
        },
    ],
}

STIFFENER_DETAILS_SCHEMA = {
    "id": "stiffener_details_tab",
    "overview": [
        {
            "id": "member_id",
            "label": "Select Member ID:",
            "type": "combo_dynamic",
            "bind": "girder_member_combo",
        },
    ],
    "stiffener_inputs": [
        {
            "id": "bearing_stiffeners_each_end",
            "label": "No. of Bearing Stiffeners\n(on one side only):",
            "type": "combo",
            "choices": VALUES_BEARING_STIFFENER_COUNT,
            "default": str(STIFFENER_DETAILS_DEFAULTS.get("bearing_stiffeners_each_end", "2")),
            "bind": "bearing_count_combo",
        },
        {
            "id": "bearing_spacing_mm",
            "label": "Bearing Stiffener Spacing (mm):",
            "type": "line",
            "validator": {"type": "int_range", "bottom": 1, "top": 1000000000},
            "bind": "bearing_spacing_input",
        },
        {
            "id": "bearing_thickness",
            "label": "Bearing Stiffener Thickness (mm):",
            "type": "mode_value",
            "mode_choices": VALUES_PROFILE_SCOPE,
            "default_mode": VALUES_PROFILE_SCOPE[0],
            "bind_mode": "bearing_thick_combo",
            "bind_value": "bearing_thick_value_combo",
        },
        {
            "id": "bearing_outstand_mm",
            "label": "Outstand of Bearing Stiffener (mm):",
            "type": "line",
            "bind": "bearing_outstand_input",
        },
        {
            "id": "intermediate_stiffener",
            "label": "Intermediate Stiffener:",
            "type": "combo",
            "choices": VALUES_NO_YES,
            "bind": "intermediate_combo",
        },
        {
            "id": "intermediate_spacing_mm",
            "label": "Intermediate Stiffener Spacing:",
            "type": "line",
            "validator": {"type": "int_range", "bottom": 1, "top": 1000000000},
            "default": "NA",
            "bind": "intermediate_spacing_input",
        },
        {
            "id": "intermediate_thickness",
            "label": "Intermediate Stiffener Thickness (mm):",
            "type": "mode_value",
            "mode_choices": VALUES_PROFILE_SCOPE,
            "default_mode": VALUES_PROFILE_SCOPE[0],
            "bind_mode": "intermediate_thick_combo",
            "bind_value": "intermediate_thick_value_combo",
        },
        {
            "id": "intermediate_outstand_mm",
            "label": "Outstand of Intermediate Stiffener (mm):",
            "type": "line",
            "bind": "intermediate_outstand_input",
        },
        {
            "id": "longitudinal_stiffener",
            "label": "Longitudinal Stiffener:",
            "type": "combo",
            "choices": VALUES_LONGITUDINAL_STIFFENER,
            "bind": "longitudinal_combo",
        },
        {
            "id": "longitudinal_thickness",
            "label": "Longitudinal Stiffener Thickness (mm):",
            "type": "mode_value",
            "mode_choices": VALUES_PROFILE_SCOPE,
            "default_mode": VALUES_PROFILE_SCOPE[0],
            "bind_mode": "long_thick_combo",
            "bind_value": "long_thick_value_combo",
        },
    ],
    "web_buckling_inputs": [
        {
            "id": "shear_buckling_method",
            "label": "Shear Buckling Design Method:",
            "type": "combo",
            "choices": VALUES_STIFFENER_DESIGN,
            "bind": "method_combo",
        },
    ],
}

CROSS_BRACING_DETAILS_SCHEMA = {
    "id": "cross_bracing_details_tab",
    "overview": [
        {
            "id": "select_girders",
            "label": "Select Girders:",
            "type": "combo_dynamic",
            "bind": "select_girders_combo",
        },
        {
            "id": "member_id",
            "label": "Member ID:",
            "type": "line",
            "read_only": True,
            "bind": "member_id_display",
        },
    ],
    "section_inputs": [
        {
            "id": "design",
            "label": "Design:",
            "type": "combo",
            "choices": VALUES_GIRDER_DESIGN_MODE,
            "bind": "design_combo",
            "default": "Optimized",
        },
        {
            "id": "bracing_type",
            "label": "Type of Bracing:",
            "type": "combo",
            "choices": ["K-Bracing", "X-Bracing"],
            "bind": "bracing_type_combo",
        },
        {
            "id": "bracing_section_type",
            "label": "Bracing Section Type:",
            "type": "combo",
            "choices": [
                "Angle",
                "Double Angle (Long Leg)",
                "Double Angle (Short Leg)",
                "Channel",
                "Double Channel",
            ],
            "bind": "bracing_section_type_combo",
        },
        {
            "id": "bracing_section",
            "label": "Bracing Section Designation:",
            "type": "combo_dynamic",
            "bind": "bracing_section_combo",
        },
        {
            "id": "top_chord_enabled",
            "label": "Top Chord:",
            "type": "checkbox",
            "bind": "top_chord_checkbox",
            "default": False,
        },
        {
            "id": "top_chord_type",
            "label": "Top Chord Section Type:",
            "type": "combo",
            "choices": [
                "Angle",
                "Double Angle (Long Leg)",
                "Double Angle (Short Leg)",
                "Channel",
                "Double Channel",
            ],
            "bind": "top_chord_type_combo",
        },
        {
            "id": "top_chord_size",
            "label": "Top Chord Section Designation:",
            "type": "combo_dynamic",
            "bind": "top_chord_size_combo",
        },
        {
            "id": "bottom_chord_enabled",
            "label": "Bottom Chord:",
            "type": "checkbox",
            "bind": "bottom_chord_checkbox",
            "default": True,
        },
        {
            "id": "bottom_chord_type",
            "label": "Bottom Chord Section Type:",
            "type": "combo",
            "choices": [
                "Angle",
                "Double Angle (Long Leg)",
                "Double Angle (Short Leg)",
                "Channel",
                "Double Channel",
            ],
            "bind": "bottom_chord_type_combo",
        },
        {
            "id": "bottom_chord_size",
            "label": "Bottom Chord Section Designation:",
            "type": "combo_dynamic",
            "bind": "bottom_chord_size_combo",
        },
        {
            "id": "spacing",
            "label": "Spacing (m):",
            "type": "line",
            "default": "3",
            "validator": {"type": "double_range", "bottom": 0.01, "top": 100000.0, "decimals": 2},
            "bind": "spacing_input",
        },
    ],
}

END_DIAPHRAGM_DETAILS_SCHEMA = {
    "id": "end_diaphragm_details_tab",
    "views": {
        "Cross Bracing": {
            "overview": [
                {
                    "id": "type_selector",
                    "label": "Type:",
                    "type": "combo",
                    "choices": VALUES_END_DIAPHRAGM_TYPE,
                    "default": "Cross Bracing",
                },
            ],
            "section_inputs": [
                {
                    "id": "design",
                    "label": "Design:",
                    "type": "combo",
                    "choices": VALUES_GIRDER_DESIGN_MODE,
                    "default": "Optimized",
                    "bind": "cross_design_combo",
                },
                {
                    "id": "bracing_type",
                    "label": "Type of Bracing:",
                    "type": "combo",
                    "choices": ["K-Bracing", "X-Bracing"],
                    "bind": "cross_bracing_type_combo",
                },
                {
                    "id": "bracing_section_type",
                    "label": "Bracing Section Type:",
                    "type": "combo",
                    "choices": [
                        "Angle",
                        "Double Angle (Long Leg)",
                        "Double Angle (Short Leg)",
                        "Channel",
                        "Double Channel",
                    ],
                    "bind": "cross_bracing_section_type_combo",
                },
                {
                    "id": "bracing_section",
                    "label": "Bracing Section Designation:",
                    "type": "combo_dynamic",
                    "bind": "cross_bracing_section_combo",
                },
                {
                    "id": "top_chord_enabled",
                    "label": "Top Chord:",
                    "type": "checkbox",
                    "default": False,
                    "bind": "cross_top_chord_checkbox",
                },
                {
                    "id": "top_chord_type",
                    "label": "Top Chord Section Type:",
                    "type": "combo",
                    "choices": [
                        "Angle",
                        "Double Angle (Long Leg)",
                        "Double Angle (Short Leg)",
                        "Channel",
                        "Double Channel",
                    ],
                    "bind": "cross_top_chord_type_combo",
                },
                {
                    "id": "top_chord_size",
                    "label": "Top Chord Section Designation:",
                    "type": "combo_dynamic",
                    "bind": "cross_top_chord_size_combo",
                },
                {
                    "id": "bottom_chord_enabled",
                    "label": "Bottom Chord:",
                    "type": "checkbox",
                    "default": True,
                    "bind": "cross_bottom_chord_checkbox",
                },
                {
                    "id": "bottom_chord_type",
                    "label": "Bottom Chord Section Type:",
                    "type": "combo",
                    "choices": [
                        "Angle",
                        "Double Angle (Long Leg)",
                        "Double Angle (Short Leg)",
                        "Channel",
                        "Double Channel",
                    ],
                    "bind": "cross_bottom_chord_type_combo",
                },
                {
                    "id": "bottom_chord_size",
                    "label": "Bottom Chord Section Designation:",
                    "type": "combo_dynamic",
                    "bind": "cross_bottom_chord_size_combo",
                },
            ],
        },
        "Rolled Beam": {
            "overview": [
                {
                    "id": "type_selector",
                    "label": "Type:",
                    "type": "combo",
                    "choices": VALUES_END_DIAPHRAGM_TYPE,
                    "default": "Rolled Beam",
                },
            ],
            "section_inputs": [
                {
                    "id": "design",
                    "label": "Design:",
                    "type": "combo",
                    "choices": VALUES_GIRDER_DESIGN_MODE,
                    "default": "Optimized",
                    "bind": "rolled_design_combo",
                },
                {
                    "id": "is_section",
                    "label": "IS Section:",
                    "type": "combo_dynamic",
                    "bind": "rolled_is_section_combo",
                },
            ],
        },
        "Welded Beam": {
            "overview": [
                {
                    "id": "type_selector",
                    "label": "Type:",
                    "type": "combo",
                    "choices": VALUES_END_DIAPHRAGM_TYPE,
                    "default": "Welded Beam",
                },
            ],
            "section_inputs": [
                {
                    "id": "design",
                    "label": "Design:",
                    "type": "combo",
                    "choices": VALUES_GIRDER_DESIGN_MODE,
                    "default": "Optimized",
                    "bind": "welded_design_combo",
                },
                {
                    "id": "symmetry",
                    "label": "Symmetry:",
                    "type": "combo",
                    "choices": VALUES_GIRDER_SYMMETRY,
                    "bind": "welded_symmetry_combo",
                },
            ],
        },
    },
}

MEMBER_PROPERTIES_SCHEMA_V1 = {
    "version": 1,
    "tabs": {
        "girder_details": {
            "id": "girder_details",
            "title": "Girder Details",
            "overview": GIRDER_DETAILS_SCHEMA.get("overview", []),
            "section_inputs": GIRDER_DETAILS_SCHEMA.get("section_inputs", []),
        },
        "stiffener_details": {
            "id": "stiffener_details",
            "title": "Stiffener Details",
            "overview": STIFFENER_DETAILS_SCHEMA.get("overview", []),
            "stiffener_inputs": STIFFENER_DETAILS_SCHEMA.get("stiffener_inputs", []),
            "web_buckling_inputs": STIFFENER_DETAILS_SCHEMA.get("web_buckling_inputs", []),
        },
        "cross_bracing_details": {
            "id": "cross_bracing_details",
            "title": "Cross-Bracing Details",
            "overview": CROSS_BRACING_DETAILS_SCHEMA.get("overview", []),
            "section_inputs": CROSS_BRACING_DETAILS_SCHEMA.get("section_inputs", []),
        },
        "end_diaphragm_details": {
            "id": "end_diaphragm_details",
            "title": "End Diaphragm Details",
            "views": END_DIAPHRAGM_DETAILS_SCHEMA.get("views", {}),
        },
    },
}
