from osdagbridge.core.utils.common import VALUES_GIRDER_DESIGN_MODE

CROSS_BRACING_DETAILS_SCHEMA = {
    "id": "cross_bracing_details_tab",
    "overview": [
        {
            "id": "cad_preview",
            "type": "cad",
            "widget": "BracingLayoutCadWidget",
            "bind": "bracing_cad_preview",
            "min_height": 200,
        },
        {
            "id": "select_girders",
            "label": "Select Girders:",
            "type": "combo_dynamic",
            "bind": "select_girders_combo",
            "on_change": "_on_girder_pair_changed",
        },
        {
            "id": "member_id",
            "label": "Member ID:",
            "type": "line",
            "read_only": True,
            "bind": "member_id_display",
        },
    ],
    "section_inputs": [
        {
            "id": "design",
            "label": "Design:",
            "type": "combo",
            "choices": VALUES_GIRDER_DESIGN_MODE,
            "bind": "design_combo",
            "default": "Optimized",
        },
        {
            "id": "bracing_type",
            "label": "Type of Bracing:",
            "type": "combo",
            "choices": ["K-Bracing", "X-Bracing"],
            "bind": "bracing_type_combo",
        },
        {
            "id": "bracing_section_type",
            "label": "Bracing Section Type:",
            "type": "combo",
            "choices": [
                "Angle",
                "Double Angle (Long Leg)",
                "Double Angle (Short Leg)",
                "Channel",
                "Double Channel",
            ],
            "bind": "bracing_section_type_combo",
        },
        {
            "id": "bracing_section",
            "label": "Bracing Section Designation:",
            "type": "combo_dynamic",
            "bind": "bracing_section_combo",
        },
        {
            "id": "top_chord_enabled",
            "label": "Top Chord:",
            "type": "checkbox",
            "bind": "top_chord_checkbox",
            "default": False,
        },
        {
            "id": "top_chord_type",
            "label": "Top Chord Section Type:",
            "type": "combo",
            "choices": [
                "Angle",
                "Double Angle (Long Leg)",
                "Double Angle (Short Leg)",
                "Channel",
                "Double Channel",
            ],
            "bind": "top_chord_type_combo",
        },
        {
            "id": "top_chord_size",
            "label": "Top Chord Section Designation:",
            "type": "combo_dynamic",
            "bind": "top_chord_size_combo",
        },
        {
            "id": "bottom_chord_enabled",
            "label": "Bottom Chord:",
            "type": "checkbox",
            "bind": "bottom_chord_checkbox",
            "default": True,
        },
        {
            "id": "bottom_chord_type",
            "label": "Bottom Chord Section Type:",
            "type": "combo",
            "choices": [
                "Angle",
                "Double Angle (Long Leg)",
                "Double Angle (Short Leg)",
                "Channel",
                "Double Channel",
            ],
            "bind": "bottom_chord_type_combo",
        },
        {
            "id": "bottom_chord_size",
            "label": "Bottom Chord Section Designation:",
            "type": "combo_dynamic",
            "bind": "bottom_chord_size_combo",
        },
        {
            "id": "spacing",
            "label": "Spacing (m):",
            "type": "line",
            "default": "3",
            "validator": {"type": "double_range", "bottom": 0.01, "top": 100000.0, "decimals": 2},
            "bind": "spacing_input",
        },
    ],
}
