from osdagbridge.core.utils.common import (
    SAIL_APPROVED_THICKNESS_VALUES,
    VALUES_GIRDER_DESIGN_MODE,
    VALUES_GIRDER_SPAN_MODE,
    VALUES_GIRDER_SUPPORT_TYPE,
    VALUES_GIRDER_SYMMETRY,
    VALUES_GIRDER_TYPE,
    VALUES_PROFILE_SCOPE,
    VALUES_TORSIONAL_RESTRAINT,
    VALUES_WARPING_RESTRAINT,
    VALUES_WEB_TYPE,
)

GIRDER_DETAILS_SCHEMA = {
    "id": "girder_details_tab",
    "defaults": {
        "member_length_m": 30.0,
        "distance_start_m": 0.0,
        "max_girder_count": 20,
    },
    "SAIL_APPROVED_THICKNESS_VALUES": SAIL_APPROVED_THICKNESS_VALUES,
    "thickness_values_mm": SAIL_APPROVED_THICKNESS_VALUES,
    "overview": [
        {
            "id": "cad_preview_section",
            "type": "cad_row",
            "widgets": [
                {
                    "id": "girder_cad",
                    "type": "cad",
                    "widget": "GirderCad2DView",
                    "bind": "girder_cad_view",
                    "stretch": 4,
                },
                {
                    "id": "cad_controls",
                    "type": "section_box",
                    "fields": [
                        {
                            "id": "cross_view_btn",
                            "type": "button",
                            "text": "Cross Section",
                            "bind": "cross_section_view_btn",
                            "on_click": "_on_cross_view_clicked",
                        },
                        {
                            "id": "side_view_btn",
                            "type": "button",
                            "text": "Side View",
                            "bind": "side_view_btn",
                            "on_click": "_on_side_view_clicked",
                        }
                    ],
                    "stretch": 1,
                }
            ],
            "min_height": 180,
        },
        {
            "id": "girder_selection_row",
            "type": "section_box",
            "rows": [
                [
                    {
                        "id": "select_girder",
                        "label": "Select Girder:",
                        "type": "combo_dynamic",
                        "bind": "girder_dropdown",
                        "on_change": "_on_girder_dropdown_changed",
                        "include_all": True,
                    },
                    {
                        "id": "span",
                        "label": "Span:",
                        "type": "combo",
                        "choices": VALUES_GIRDER_SPAN_MODE,
                        "bind": "span_combo",
                    },
                    {
                        "id": "total_span",
                        "label": "Total Span (m):",
                        "type": "line",
                        "default": "30",
                        "read_only": True,
                        "bind": "length_input",
                    }
                ]
            ]
        },
        {
            "id": "copy_buttons_row",
            "type": "section_box",
            "rows": [
                [
                    {
                        "id": "apply_exterior",
                        "type": "button",
                        "text": "Apply changes to exterior girders",
                        "bind": "apply_exterior_button",
                        "on_click": "_on_apply_exterior_clicked",
                    },
                    {
                        "id": "apply_interior",
                        "type": "button",
                        "text": "Apply changes to interior girder",
                        "bind": "apply_interior_button",
                        "on_click": "_on_apply_interior_clicked",
                    }
                ]
            ]
        }
    ],
    "segment_manager": {
        "table_headers": ["Member ID", "Start (m)", "End (m)", "Length (m)", "Action"],
        "action_column_width": 132,
    },
    "cad_view": {
        "buttons": [
            {"id": "cross_section", "label": "Cross Section", "mode": "cross", "width": 130, "height": 32},
            {"id": "side_view", "label": "Side View", "mode": "side", "width": 130, "height": 32},
        ]
    },
    "section_inputs": [
        {
            "id": "design",
            "label": "Design:",
            "type": "combo",
            "choices": VALUES_GIRDER_DESIGN_MODE,
            "bind": "design_combo",
            "legacy_payload_key": "design_mode",
            "visible_for": ["welded"],
        },
        {
            "id": "type",
            "label": "Type:",
            "type": "combo",
            "choices": VALUES_GIRDER_TYPE,
            "bind": "type_combo",
            "legacy_payload_key": "girder_type",
        },
        {
            "id": "symmetry",
            "label": "Symmetry:",
            "type": "combo",
            "choices": VALUES_GIRDER_SYMMETRY,
            "bind": "symmetry_combo",
            "row_bucket": "symmetry_row",
            "legacy_payload_key": "symmetry",
            "visible_for": ["welded"],
        },
        {
            "id": "depth",
            "label": "Total Depth, d (mm):",
            "type": "line_with_bounds",
            "bounds_key": "total_depth",
            "bounds_default": {"lower": 200.0, "upper": 2000.0, "increment": 25.0},
            "bind": "total_depth_input",
            "bind_widget": "total_depth_widget",
            "bind_bounds_button": "total_depth_bounds_button",
            "legacy_welded_key": "total_depth_mm",
            "legacy_welded_bounds_key": "total_depth_bounds",
            "visible_for": ["welded"],
        },
        {
            "id": "top_flange_width",
            "label": "Width of Top Flange, t<sub>fw</sub> (mm):",
            "type": "line_with_bounds",
            "bounds_key": "top_width",
            "bounds_default": {"lower": 100.0, "upper": 1000.0, "increment": 10.0},
            "bind": "top_width_input",
            "bind_widget": "top_width_widget",
            "bind_bounds_button": "top_width_bounds_button",
            "legacy_welded_key": "top_flange_width_mm",
            "legacy_welded_bounds_key": "top_flange_width_bounds",
            "visible_for": ["welded"],
        },
        {
            "id": "top_flange_thickness",
            "label": "Top Flange Thickness, t<sub>ft</sub> (mm):",
            "type": "mode_line",
            "mode_choices": VALUES_PROFILE_SCOPE,
            "default_mode": "All",
            "bind_mode": "top_thickness_combo",
            "bind_value": "top_thickness_value_input",
            "bind_wrapper": "top_thickness_widget",
            "thickness_key": "top_thickness",
            "legacy_welded_mode_key": "top_thickness_mode",
            "legacy_welded_value_key": "top_thickness_value_mm",
            "visible_for": ["welded"],
        },
        {
            "id": "bottom_flange_width",
            "label": "Width of Bottom Flange, b<sub>fw</sub> (mm):",
            "type": "line_with_bounds",
            "bounds_key": "bottom_width",
            "bounds_default": {"lower": 100.0, "upper": 1000.0, "increment": 10.0},
            "bind": "bottom_width_input",
            "bind_widget": "bottom_width_widget",
            "bind_bounds_button": "bottom_width_bounds_button",
            "legacy_welded_key": "bottom_flange_width_mm",
            "legacy_welded_bounds_key": "bottom_flange_width_bounds",
            "visible_for": ["welded"],
        },
        {
            "id": "bottom_flange_thickness",
            "label": "Bottom Flange Thickness, b<sub>ft</sub> (mm):",
            "type": "mode_line",
            "mode_choices": VALUES_PROFILE_SCOPE,
            "default_mode": "All",
            "bind_mode": "bottom_thickness_combo",
            "bind_value": "bottom_thickness_value_input",
            "bind_wrapper": "bottom_thickness_widget",
            "thickness_key": "bottom_thickness",
            "legacy_welded_mode_key": "bottom_thickness_mode",
            "legacy_welded_value_key": "bottom_thickness_value_mm",
            "visible_for": ["welded"],
        },
        {
            "id": "support_type",
            "label": "Support Type:",
            "type": "combo",
            "choices": VALUES_GIRDER_SUPPORT_TYPE,
            "bind": "support_type_combo",
            "visible_for": ["welded"],
        },
        {
            "id": "support_width",
            "label": "Support Width (mm):",
            "type": "line",
            "validator": {"type": "double_range", "bottom": 0.0, "top": 1000000.0, "decimals": 3},
            "bind": "support_width_input",
            "legacy_welded_key": "support_width_mm",
            "visible_for": ["welded"],
        },
        {
            "id": "web_thickness",
            "label": "Web Thickness, w<sub>t</sub> (mm):",
            "type": "mode_line",
            "mode_choices": VALUES_PROFILE_SCOPE,
            "default_mode": "All",
            "bind_mode": "web_thickness_combo",
            "bind_value": "web_thickness_value_input",
            "bind_wrapper": "web_thickness_widget",
            "thickness_key": "web_thickness",
            "legacy_welded_mode_key": "web_thickness_mode",
            "legacy_welded_value_key": "web_thickness_value_mm",
            "visible_for": ["welded"],
        },
        {
            "id": "is_section",
            "label": "IS Section:",
            "type": "combo",
            "choices": [
                "ISMB 500", "ISMB 550", "ISMB 600",
                "ISWB 500", "ISWB 550", "ISWB 600",
            ],
            "bind": "is_section_combo",
            "legacy_payload_key": "rolled_section",
            "visible_for": ["rolled"],
        },
        {
            "id": "torsional_restraint",
            "label": "Torsional Restraint:",
            "type": "combo",
            "choices": VALUES_TORSIONAL_RESTRAINT,
            "bind": "torsion_combo",
            "aliases": ["torsion"],
            "legacy_payload_key": "torsional_restraint",
        },
        {
            "id": "warping_restraint",
            "label": "Warping Restraint:",
            "type": "combo",
            "choices": VALUES_WARPING_RESTRAINT,
            "bind": "warping_combo",
            "aliases": ["warping"],
            "legacy_payload_key": "warping_restraint",
        },
        {
            "id": "web_type",
            "label": "Web Type:",
            "type": "combo",
            "choices": VALUES_WEB_TYPE,
            "bind": "web_type_combo",
            "row_bucket": "web_type_row",
            "legacy_payload_key": "web_type",
            "visible_for": ["welded"],
        },
    ],
}
