from osdagbridge.core.utils.common import (
    VALUES_BEARING_STIFFENER_COUNT,
    VALUES_LONGITUDINAL_STIFFENER,
    VALUES_PROFILE_SCOPE,
    VALUES_STIFFENER_DESIGN,
    VALUES_NO_YES,
    STIFFENER_DETAILS_DEFAULTS,
)

STIFFENER_DETAILS_SCHEMA = {
    "id": "stiffener_details_tab",
    "description": {
        "id": "stiffener_description",
        "bind": "description_text",
        "placeholder": "Describe stiffener assumptions or notes here.",
        "min_height": 210,
    },
    "overview": [
        {
            "id": "cad_preview",
            "type": "cad_row",
            "widgets": [
                {
                    "id": "stiffener_preview",
                    "widget": "StiffenerCadPreviewWidget",
                    "bind": "stiffener_cad_preview",
                    "update_method": "set_data",
                    "reactive_sources": ["girder_member_combo"],
                    "stretch": 3,
                },
                {
                    "id": "stiffener_legend",
                    "type": "legend",
                    "title": "Legend",
                    "items": [
                        {"label": "Bearing Stiffener", "color": "#90AF13"},
                        {"label": "Intermediate Stiffener", "color": "#6B7D20"},
                        {"label": "Longitudinal Stiffener", "color": "#4a4a4a"},
                    ],
                    "stretch": 1,
                },
            ],
            "min_height": 240,
        },
        {
            "id": "member_id",
            "label": "Select Member ID:",
            "type": "combo_dynamic",
            "bind": "girder_member_combo",
            "on_change": "_on_member_changed",
        },
        {
            "id": "apply_all",
            "type": "button",
            "label": "Apply changes to all custom",
            "bind": "apply_to_all_btn",
            "on_click": "_apply_current_to_all_members",
            "alignment": "right",
        },
    ],
    "stiffener_inputs": [
        {
            "id": "bearing_stiffeners_each_end",
            "label": "No. of Bearing Stiffeners\n(on one side only):",
            "type": "combo",
            "choices": VALUES_BEARING_STIFFENER_COUNT,
            "default": str(STIFFENER_DETAILS_DEFAULTS.get("bearing_stiffeners_each_end", "2")),
            "bind": "bearing_count_combo",
        },
        {
            "id": "bearing_spacing_mm",
            "label": "Bearing Stiffener Spacing (mm):",
            "type": "line",
            "validator": {"type": "int_range", "bottom": 1, "top": 1000000000},
            "bind": "bearing_spacing_input",
        },
        {
            "id": "bearing_thickness",
            "label": "Bearing Stiffener Thickness (mm):",
            "type": "mode_value",
            "mode_choices": VALUES_PROFILE_SCOPE,
            "default_mode": VALUES_PROFILE_SCOPE[0],
            "bind_mode": "bearing_thick_combo",
            "bind_value": "bearing_thick_value_combo",
        },
        {
            "id": "bearing_outstand_mm",
            "label": "Outstand of Bearing Stiffener (mm):",
            "type": "line",
            "bind": "bearing_outstand_input",
        },
        {
            "id": "intermediate_stiffener",
            "label": "Intermediate Stiffener:",
            "type": "combo",
            "choices": VALUES_NO_YES,
            "bind": "intermediate_combo",
        },
        {
            "id": "intermediate_spacing_mm",
            "label": "Intermediate Stiffener Spacing:",
            "type": "line",
            "validator": {"type": "int_range", "bottom": 1, "top": 1000000000},
            "default": "NA",
            "bind": "intermediate_spacing_input",
        },
        {
            "id": "intermediate_thickness",
            "label": "Intermediate Stiffener Thickness (mm):",
            "type": "mode_value",
            "mode_choices": VALUES_PROFILE_SCOPE,
            "default_mode": VALUES_PROFILE_SCOPE[0],
            "bind_mode": "intermediate_thick_combo",
            "bind_value": "intermediate_thick_value_combo",
        },
        {
            "id": "intermediate_outstand_mm",
            "label": "Outstand of Intermediate Stiffener (mm):",
            "type": "line",
            "bind": "intermediate_outstand_input",
        },
        {
            "id": "longitudinal_stiffener",
            "label": "Longitudinal Stiffener:",
            "type": "combo",
            "choices": VALUES_LONGITUDINAL_STIFFENER,
            "bind": "longitudinal_combo",
        },
        {
            "id": "longitudinal_thickness",
            "label": "Longitudinal Stiffener Thickness (mm):",
            "type": "mode_value",
            "mode_choices": VALUES_PROFILE_SCOPE,
            "default_mode": VALUES_PROFILE_SCOPE[0],
            "bind_mode": "long_thick_combo",
            "bind_value": "long_thick_value_combo",
        },
    ],
    "web_buckling_inputs": [
        {
            "id": "shear_buckling_method",
            "label": "Shear Buckling Design Method:",
            "type": "combo",
            "choices": VALUES_STIFFENER_DESIGN,
            "bind": "method_combo",
        },
    ],
}
