WIND_LOAD_TAB_SCHEMA = {
    "id": "wind_load_tab",
    "label_width": 260,
    "field_width": 140,
    "field_height": 28,
    "sections": [
        {
            "id": "wind_inputs_section",
            "title": "Wind Load (WL) Inputs",
            "type": "input_group",
            "fields": [
                {
                    "id": "basic_wind_speed",
                    "label": "Basic Wind Speed, V<sub>b</sub> (m/s)",
                    "type": "line",
                    "read_only": True,
                    "enabled": False,
                    "bind": "basic_wind_speed_input",
                },
                {
                    "id": "avg_exposed_height",
                    "label": "Average Exposed Height, H (m)",
                    "type": "line",
                    "default": "10",
                    "placeholder": "10",
                    "bind": "avg_exposed_height_input",
                },
                {
                    "id": "terrain_type",
                    "label": "Type of Terrain",
                    "type": "combo",
                    "choices": ["Plain Terrain", "Terrain with \nObstructions"],
                    "default": "Plain Terrain",
                    "bind": "terrain_type_combo",
                },
                {
                    "id": "site_topography",
                    "label": "Site Topography",
                    "type": "combo",
                    "choices": ["Flat", "Hill, ridge, escarpment or cliff"],
                    "default": "Flat",
                    "bind": "site_topography_combo",
                },
                {
                    "id": "gust_factor",
                    "label": "Gust Factor, G",
                    "type": "mode_line",
                    "mode_choices": ["As per Code", "Custom"],
                    "default_mode": "As per Code",
                    "bind_mode": "gust_factor_combo",
                    "bind_value": "gust_factor_value",
                    "default_value": "2",
                    "placeholder": "2",
                    "conditions": [{"when": "gust_factor_combo", "equals": "Custom", "action": "enable"}],
                },
                {
                    "id": "drag_coeff",
                    "label": "Drag Coefficient, C<sub>D</sub>",
                    "type": "mode_line",
                    "mode_choices": ["As per Code", "Custom"],
                    "default_mode": "As per Code",
                    "bind_mode": "drag_coeff_combo",
                    "bind_value": "drag_coeff_value",
                    "default_value": "",
                    "placeholder": "Custom Value",
                    "conditions": [{"when": "drag_coeff_combo", "equals": "Custom", "action": "enable"}],
                },
                {
                    "id": "drag_coeff_ll",
                    "label": "Drag Coefficient against Live Load, C<sub>DLL</sub>",
                    "type": "mode_line",
                    "mode_choices": ["As per Code", "Custom"],
                    "default_mode": "As per Code",
                    "bind_mode": "drag_coeff_ll_combo",
                    "bind_value": "drag_coeff_ll_value",
                    "default_value": "1.2",
                    "placeholder": "1.2",
                    "conditions": [{"when": "drag_coeff_ll_combo", "equals": "Custom", "action": "enable"}],
                },
                {
                    "id": "lift_coeff",
                    "label": "Lift Coefficient, C<sub>L</sub>",
                    "type": "mode_line",
                    "mode_choices": ["As per Code", "Custom"],
                    "default_mode": "As per Code",
                    "bind_mode": "lift_coeff_combo",
                    "bind_value": "lift_coeff_value",
                    "default_value": "0.75",
                    "placeholder": "0.75",
                    "conditions": [{"when": "lift_coeff_combo", "equals": "Custom", "action": "enable"}],
                },
                {
                    "id": "super_area_elev",
                    "label": "Superstructure Area in Elevation, A<sub>1</sub> (m²)",
                    "type": "mode_line",
                    "mode_choices": ["Automatic", "Custom"],
                    "default_mode": "Automatic",
                    "bind_mode": "super_area_elev_combo",
                    "bind_value": "super_area_elev_value",
                    "default_value": "",
                    "placeholder": "Custom Value",
                    "conditions": [{"when": "super_area_elev_combo", "equals": "Custom", "action": "enable"}],
                },
                {
                    "id": "super_area_plain",
                    "label": "Superstructure Area in Plain, A<sub>3</sub> (m²)",
                    "type": "mode_line",
                    "mode_choices": ["Automatic", "Custom"],
                    "default_mode": "Automatic",
                    "bind_mode": "super_area_plain_combo",
                    "bind_value": "super_area_plain_value",
                    "default_value": "",
                    "placeholder": "Custom Value",
                    "conditions": [{"when": "super_area_plain_combo", "equals": "Custom", "action": "enable"}],
                },
                {
                    "id": "exposed_frontal_area",
                    "label": "Exposed Frontal Area of Live Load, A<sub>1LL</sub> (m²)",
                    "type": "mode_line",
                    "mode_choices": ["Automatic", "Custom"],
                    "default_mode": "Automatic",
                    "bind_mode": "exposed_frontal_area_combo",
                    "bind_value": "exposed_frontal_area_value",
                    "default_value": "",
                    "placeholder": "Custom Value",
                    "conditions": [{"when": "exposed_frontal_area_combo", "equals": "Custom", "action": "enable"}],
                },
                {
                    "id": "wind_ecc_deck",
                    "label": "Wind Load Eccentricity from \nTop of Deck (m)",
                    "type": "mode_line",
                    "mode_choices": ["As per Code", "Custom"],
                    "default_mode": "As per Code",
                    "bind_mode": "wind_ecc_deck_combo",
                    "bind_value": "wind_ecc_deck_value",
                    "default_value": "",
                    "placeholder": "Custom Value",
                    "conditions": [{"when": "wind_ecc_deck_combo", "equals": "Custom", "action": "enable"}],
                },
                {
                    "id": "wind_ll_ecc",
                    "label": "Wind on Live Load Eccentricity from \nTop of Deck (m)",
                    "type": "mode_line",
                    "mode_choices": ["As per Code", "Custom"],
                    "default_mode": "As per Code",
                    "bind_mode": "wind_ll_ecc_combo",
                    "bind_value": "wind_ll_ecc_value",
                    "default_value": "",
                    "placeholder": "Custom Value",
                    "conditions": [{"when": "wind_ll_ecc_combo", "equals": "Custom", "action": "enable"}],
                },
            ],
        },
        {
            "id": "computed_values_section",
            "title": "Computed Values",
            "type": "computed_group",
            "fields": [
                {
                    "id": "hourly_mean_wind",
                    "label": "Hourly Mean Wind Speed, V<sub>z</sub> (m/s)",
                    "type": "computed",
                    "bind": "hourly_mean_wind",
                },
                {
                    "id": "hourly_wind_pressure",
                    "label": "Hourly Wind Pressure, P<sub>z</sub> (N/m²)",
                    "type": "computed",
                    "bind": "hourly_wind_pressure",
                },
                {
                    "id": "transverse_wind_force",
                    "label": "Transverse Wind Force, F<sub>T</sub> (N)",
                    "type": "computed",
                    "bind": "transverse_wind_force",
                },
                {
                    "id": "longitudinal_wind_force",
                    "label": "Longitudinal Wind Force, F<sub>L</sub> (N)",
                    "type": "computed",
                    "bind": "longitudinal_wind_force",
                },
                {
                    "id": "vertical_wind_force",
                    "label": "Vertical Wind Force, F<sub>V</sub> (N)",
                    "type": "computed",
                    "bind": "vertical_wind_force",
                },
                {
                    "id": "transverse_wind_ll",
                    "label": "Transverse Wind Force on Live Load, F<sub>TLL</sub> (N)",
                    "type": "computed",
                    "bind": "transverse_wind_ll",
                },
                {
                    "id": "longitudinal_wind_ll",
                    "label": "Longitudinal Wind Force on Live Load, F<sub>LLL</sub> (N)",
                    "type": "computed",
                    "bind": "longitudinal_wind_ll",
                },
            ],
        },
    ],
    "description": {
        "title": "Description Box",
        "text": (
            "Basic Wind Speed is auto-filled from software output (project location).\n\n"
        ),
    },
}
